const cities = [
    // آذربایجان شرقی
    { id: 1, name: 'تبریز', provinceId: 1 },
    { id: 2, name: 'مراغه', provinceId: 1 },
    { id: 3, name: 'میانه', provinceId: 1 },
    { id: 4, name: 'مرند', provinceId: 1 },
    { id: 5, name: 'شبستر', provinceId: 1 },
    { id: 6, name: 'بناب', provinceId: 1 },
    { id: 7, name: 'آذرشهر', provinceId: 1 },
    { id: 8, name: 'اسکو', provinceId: 1 },
    { id: 9, name: 'اهر', provinceId: 1 },
    { id: 10, name: 'بستان‌آباد', provinceId: 1 },
    { id: 11, name: 'شهر جدید سهند', provinceId: 1 },
    { id: 12, name: 'جلفا', provinceId: 1 },
    { id: 13, name: 'هشترود', provinceId: 1 },
    { id: 14, name: 'کلیبر', provinceId: 1 },
    { id: 15, name: 'خداآفرین', provinceId: 1 },
    { id: 16, name: 'ورزقان', provinceId: 1 },
    { id: 17, name: 'عجب‌شیر', provinceId: 1 },
    { id: 18, name: 'سراب', provinceId: 1 },
    { id: 19, name: 'باسمنج', provinceId: 1 },
    { id: 20, name: 'تسوج', provinceId: 1 },
    { id: 21, name: 'خامنه', provinceId: 1 },
    { id: 22, name: 'شرفخانه', provinceId: 1 },
    { id: 23, name: 'شندآباد', provinceId: 1 },
    { id: 24, name: 'سیس', provinceId: 1 },
    { id: 25, name: 'صوفیان', provinceId: 1 },
    { id: 26, name: 'ایلخچی', provinceId: 1 },
    { id: 27, name: 'خسروشاه', provinceId: 1 },
    { id: 28, name: 'بندر شرفخانه', provinceId: 1 },
    { id: 29, name: 'زنوز', provinceId: 1 },
    { id: 30, name: 'آقکند', provinceId: 1 },

    // آذربایجان غربی
    { id: 31, name: 'ارومیه', provinceId: 2 },
    { id: 32, name: 'خوی', provinceId: 2 },
    { id: 33, name: 'مهاباد', provinceId: 2 },
    { id: 34, name: 'میاندوآب', provinceId: 2 },
    { id: 35, name: 'سلماس', provinceId: 2 },
    { id: 36, name: 'بوکان', provinceId: 2 },
    { id: 37, name: 'شاهین‌دژ', provinceId: 2 },
    { id: 38, name: 'پیرانشهر', provinceId: 2 },
    { id: 39, name: 'نقده', provinceId: 2 },
    { id: 40, name: 'ماکو', provinceId: 2 },
    { id: 41, name: 'سردشت', provinceId: 2 },
    { id: 42, name: 'تکاب', provinceId: 2 },
    { id: 43, name: 'اشنویه', provinceId: 2 },
    { id: 44, name: 'چالدران', provinceId: 2 },
    { id: 45, name: 'پلدشت', provinceId: 2 },
    { id: 46, name: 'شوط', provinceId: 2 },
    { id: 47, name: 'قره‌ضیاءالدین', provinceId: 2 },
    { id: 48, name: 'سیه‌چشمه', provinceId: 2 },
    { id: 49, name: 'بازرگان', provinceId: 2 },
    { id: 50, name: 'نالوس', provinceId: 2 },

    // اردبیل
    { id: 51, name: 'اردبیل', provinceId: 3 },
    { id: 52, name: 'پارس‌آباد', provinceId: 3 },
    { id: 53, name: 'خلخال', provinceId: 3 },
    { id: 54, name: 'مشگین‌شهر', provinceId: 3 },
    { id: 55, name: 'گرمی', provinceId: 3 },
    { id: 56, name: 'نمین', provinceId: 3 },
    { id: 57, name: 'نیر', provinceId: 3 },
    { id: 58, name: 'کوثر', provinceId: 3 },
    { id: 59, name: 'اصلاندوز', provinceId: 3 },
    { id: 60, name: 'بیله‌سوار', provinceId: 3 },

    // اصفهان
    { id: 61, name: 'اصفهان', provinceId: 4 },
    { id: 62, name: 'کاشان', provinceId: 4 },
    { id: 63, name: 'خمینی‌شهر', provinceId: 4 },
    { id: 64, name: 'نجف‌آباد', provinceId: 4 },
    { id: 65, name: 'شاهین‌شهر', provinceId: 4 },
    { id: 66, name: 'فولادشهر', provinceId: 4 },
    { id: 67, name: 'فولادماهان', provinceId: 4 },
    { id: 68, name: 'گلپایگان', provinceId: 4 },
    { id: 69, name: 'نطنز', provinceId: 4 },
    { id: 70, name: 'نایین', provinceId: 4 },
    { id: 71, name: 'اردستان', provinceId: 4 },
    { id: 72, name: 'شاهین‌شهر و میمه', provinceId: 4 },
    { id: 73, name: 'سمیرم', provinceId: 4 },
    { id: 74, name: 'فريدونشهر', provinceId: 4 },
    { id: 75, name: 'فريدونشهر', provinceId: 4 },
    { id: 76, name: 'دهاقان', provinceId: 4 },
    { id: 77, name: 'مبارکه', provinceId: 4 },
    { id: 78, name: 'شاهین‌شهر', provinceId: 4 },
    { id: 79, name: 'زرین‌شهر', provinceId: 4 },
    { id: 80, name: 'ورزنه', provinceId: 4 },
    { id: 81, name: 'ابریشم', provinceId: 4 },
    { id: 82, name: 'تیران', provinceId: 4 },
    { id: 83, name: 'چادگان', provinceId: 4 },
    { id: 84, name: 'خوانسار', provinceId: 4 },
    { id: 85, name: 'دولت‌آباد', provinceId: 4 },
    { id: 86, name: 'زواره', provinceId: 4 },
    { id: 87, name: 'سده', provinceId: 4 },
    { id: 88, name: 'شاهین‌شهر', provinceId: 4 },
    { id: 89, name: 'شهرضا', provinceId: 4 },
    { id: 90, name: 'علویجه', provinceId: 4 },

    // البرز
    { id: 91, name: 'کرج', provinceId: 5 },
    { id: 92, name: 'هشتگرد', provinceId: 5 },
    { id: 93, name: 'نظرآباد', provinceId: 5 },
    { id: 94, name: 'اشتهارد', provinceId: 5 },
    { id: 95, name: 'فردیس', provinceId: 5 },
    { id: 96, name: 'ساوجبلاغ', provinceId: 5 },
    { id: 97, name: 'طالقان', provinceId: 5 },
    { id: 98, name: 'ماهدشت', provinceId: 5 },
    { id: 99, name: 'گلسار', provinceId: 5 },
    { id: 100, name: 'مشکین‌دشت', provinceId: 5 },

    // ایلام
    { id: 101, name: 'ایلام', provinceId: 6 },
    { id: 102, name: 'دهلران', provinceId: 6 },
    { id: 103, name: 'آبدانان', provinceId: 6 },
    { id: 104, name: 'دره‌شهر', provinceId: 6 },
    { id: 105, name: 'مهران', provinceId: 6 },
    { id: 106, name: 'شیروان چرداول', provinceId: 6 },
    { id: 107, name: 'ملکشاهی', provinceId: 6 },
    { id: 108, name: 'بدره', provinceId: 6 },
    { id: 109, name: 'آسمان‌آباد', provinceId: 6 },
    { id: 110, name: 'ارکواز', provinceId: 6 },

    // بوشهر
    { id: 111, name: 'بوشهر', provinceId: 7 },
    { id: 112, name: 'برازجان', provinceId: 7 },
    { id: 113, name: 'گناوه', provinceId: 7 },
    { id: 114, name: 'دیر', provinceId: 7 },
    { id: 115, name: 'کنگان', provinceId: 7 },
    { id: 116, name: 'جم', provinceId: 7 },
    { id: 117, name: 'دشتی', provinceId: 7 },
    { id: 118, name: 'تنگستان', provinceId: 7 },
    { id: 119, name: 'عسلویه', provinceId: 7 },
    { id: 120, name: 'خورموج', provinceId: 7 },

    // تهران
    { id: 121, name: 'تهران', provinceId: 8 },
    { id: 122, name: 'اسلام‌شهر', provinceId: 8 },
    { id: 123, name: 'ورامین', provinceId: 8 },
    { id: 124, name: 'شهریار', provinceId: 8 },
    { id: 125, name: 'ملارد', provinceId: 8 },
    { id: 126, name: 'پاکدشت', provinceId: 8 },
    { id: 127, name: 'قدس', provinceId: 8 },
    { id: 128, name: 'ری', provinceId: 8 },
    { id: 129, name: 'پردیس', provinceId: 8 },
    { id: 130, name: 'بومهن', provinceId: 8 },
    { id: 131, name: 'فیروزکوه', provinceId: 8 },
    { id: 132, name: 'دماوند', provinceId: 8 },
    { id: 133, name: 'شمیرانات', provinceId: 8 },
    { id: 134, name: 'شهریار', provinceId: 8 },
    { id: 135, name: 'بهارستان', provinceId: 8 },
    { id: 136, name: 'قرچک', provinceId: 8 },
    { id: 137, name: 'پیشوا', provinceId: 8 },
    { id: 138, name: 'کهریزک', provinceId: 8 },
    { id: 139, name: 'لواسان', provinceId: 8 },
    { id: 140, name: 'شمیران', provinceId: 8 },

    // چهارمحال و بختیاری
    { id: 141, name: 'شهرکرد', provinceId: 9 },
    { id: 142, name: 'بروجن', provinceId: 9 },
    { id: 143, name: 'فارسان', provinceId: 9 },
    { id: 144, name: 'لردگان', provinceId: 9 },
    { id: 145, name: 'اردل', provinceId: 9 },
    { id: 146, name: 'گندمان', provinceId: 9 },
    { id: 147, name: 'سامان', provinceId: 9 },
    { id: 148, name: 'فرخ‌شهر', provinceId: 9 },
    { id: 149, name: 'هفشجان', provinceId: 9 },
    { id: 150, name: 'چلگرد', provinceId: 9 },

    // خراسان جنوبی
    { id: 151, name: 'بیرجند', provinceId: 10 },
    { id: 152, name: 'قائن', provinceId: 10 },
    { id: 153, name: 'فردوس', provinceId: 10 },
    { id: 154, name: 'طبس', provinceId: 10 },
    { id: 155, name: 'نهبندان', provinceId: 10 },
    { id: 156, name: 'درمیان', provinceId: 10 },
    { id: 157, name: 'سرایان', provinceId: 10 },
    { id: 158, name: 'سربیشه', provinceId: 10 },
    { id: 159, name: 'خوسف', provinceId: 10 },
    { id: 160, name: 'زیرکوه', provinceId: 10 },

    // خراسان رضوی
    { id: 161, name: 'مشهد', provinceId: 11 },
    { id: 162, name: 'نیشابور', provinceId: 11 },
    { id: 163, name: 'سبزوار', provinceId: 11 },
    { id: 164, name: 'تربت حیدریه', provinceId: 11 },
    { id: 165, name: 'قوچان', provinceId: 11 },
    { id: 166, name: 'تایباد', provinceId: 11 },
    { id: 167, name: 'کاشمر', provinceId: 11 },
    { id: 168, name: 'گناباد', provinceId: 11 },
    { id: 169, name: 'خلیل‌آباد', provinceId: 11 },
    { id: 170, name: 'تربت جام', provinceId: 11 },
    { id: 171, name: 'چناران', provinceId: 11 },
    { id: 172, name: 'درگز', provinceId: 11 },
    { id: 173, name: 'کلات', provinceId: 11 },
    { id: 174, name: 'سرخس', provinceId: 11 },
    { id: 175, name: 'فریمان', provinceId: 11 },
    { id: 176, name: 'بردسکن', provinceId: 11 },
    { id: 177, name: 'جوین', provinceId: 11 },
    { id: 178, name: 'خواف', provinceId: 11 },
    { id: 179, name: 'رشتخوار', provinceId: 11 },
    { id: 180, name: 'باخرز', provinceId: 11 },
    { id: 181, name: 'بجستان', provinceId: 11 },
    { id: 182, name: 'زاوه', provinceId: 11 },
    { id: 183, name: 'مه ولات', provinceId: 11 },
    { id: 184, name: 'فیروزه', provinceId: 11 },
    { id: 185, name: 'جغتای', provinceId: 11 },
    { id: 186, name: 'داورزن', provinceId: 11 },
    { id: 187, name: 'چشمه‌گیلاس', provinceId: 11 },
    { id: 188, name: 'کوهسرخ', provinceId: 11 },
    { id: 189, name: 'زبرخان', provinceId: 11 },
    { id: 190, name: 'بینالود', provinceId: 11 },

    // خراسان شمالی
    { id: 191, name: 'بجنورد', provinceId: 12 },
    { id: 192, name: 'اسفراین', provinceId: 12 },
    { id: 193, name: 'شیروان', provinceId: 12 },
    { id: 194, name: 'آشخانه', provinceId: 12 },
    { id: 195, name: 'گرمه', provinceId: 12 },
    { id: 196, name: 'جاجرم', provinceId: 12 },
    { id: 197, name: 'فاروج', provinceId: 12 },
    { id: 198, name: 'آق‌قلعه', provinceId: 12 },
    { id: 199, name: 'راز و جرگلان', provinceId: 12 },
    { id: 200, name: 'سملقان', provinceId: 12 },

    // خوزستان
    { id: 201, name: 'اهواز', provinceId: 13 },
    { id: 202, name: 'آبادان', provinceId: 13 },
    { id: 203, name: 'خرمشهر', provinceId: 13 },
    { id: 204, name: 'دزفول', provinceId: 13 },
    { id: 205, name: 'اندیمشک', provinceId: 13 },
    { id: 206, name: 'ماهشهر', provinceId: 13 },
    { id: 207, name: 'بهبهان', provinceId: 13 },
    { id: 208, name: 'آغاجاری', provinceId: 13 },
    { id: 209, name: 'رامهرمز', provinceId: 13 },
    { id: 210, name: 'مسجدسلیمان', provinceId: 13 },
    { id: 211, name: 'شادگان', provinceId: 13 },
    { id: 212, name: 'ایذه', provinceId: 13 },
    { id: 213, name: 'اندیکا', provinceId: 13 },
    { id: 214, name: 'باغ‌ملک', provinceId: 13 },
    { id: 215, name: 'گتوند', provinceId: 13 },
    { id: 216, name: 'لالی', provinceId: 13 },
    { id: 217, name: 'هویزه', provinceId: 13 },
    { id: 218, name: 'حمیدیه', provinceId: 13 },
    { id: 219, name: 'کارون', provinceId: 13 },
    { id: 220, name: 'هفتکل', provinceId: 13 },
    { id: 221, name: 'شوش', provinceId: 13 },
    { id: 222, name: 'شوشتر', provinceId: 13 },
    { id: 223, name: 'گتوند', provinceId: 13 },
    { id: 224, name: 'رامشیر', provinceId: 13 },
    { id: 225, name: 'هندیجان', provinceId: 13 },

    // زنجان
    { id: 226, name: 'زنجان', provinceId: 14 },
    { id: 227, name: 'ابهر', provinceId: 14 },
    { id: 228, name: 'خدابنده', provinceId: 14 },
    { id: 229, name: 'ماهنشان', provinceId: 14 },
    { id: 230, name: 'قیدار', provinceId: 14 },
    { id: 231, name: 'خرمدره', provinceId: 14 },
    { id: 232, name: 'ماه‌نشان', provinceId: 14 },
    { id: 233, name: 'سلطانیه', provinceId: 14 },
    { id: 234, name: 'ایجرود', provinceId: 14 },
    { id: 235, name: 'طارم', provinceId: 14 },

    // سمنان
    { id: 236, name: 'سمنان', provinceId: 15 },
    { id: 237, name: 'شاهرود', provinceId: 15 },
    { id: 238, name: 'گرمسار', provinceId: 15 },
    { id: 239, name: 'دامغان', provinceId: 15 },
    { id: 240, name: 'آرادان', provinceId: 15 },
    { id: 241, name: 'بسطام', provinceId: 15 },
    { id: 242, name: 'میامی', provinceId: 15 },
    { id: 243, name: 'کلاته خیج', provinceId: 15 },
    { id: 244, name: 'بیارجمند', provinceId: 15 },
    { id: 245, name: 'مهدی‌شهر', provinceId: 15 },

    // سیستان و بلوچستان
    { id: 246, name: 'زاهدان', provinceId: 16 },
    { id: 247, name: 'چابهار', provinceId: 16 },
    { id: 248, name: 'خاش', provinceId: 16 },
    { id: 249, name: 'ایرانشهر', provinceId: 16 },
    { id: 250, name: 'زابل', provinceId: 16 },
    { id: 251, name: 'سراوان', provinceId: 16 },
    { id: 252, name: 'کنارک', provinceId: 16 },
    { id: 253, name: 'راسک', provinceId: 16 },
    { id: 254, name: 'سرباز', provinceId: 16 },
    { id: 255, name: 'قصرقند', provinceId: 16 },
    { id: 256, name: 'میرجاوه', provinceId: 16 },
    { id: 257, name: 'زهک', provinceId: 16 },
    { id: 258, name: 'هیرمند', provinceId: 16 },
    { id: 259, name: 'هامون', provinceId: 16 },
    { id: 260, name: 'نیمروز', provinceId: 16 },

    // فارس
    { id: 261, name: 'شیراز', provinceId: 17 },
    { id: 262, name: 'مرودشت', provinceId: 17 },
    { id: 263, name: 'کازرون', provinceId: 17 },
    { id: 264, name: 'جهرم', provinceId: 17 },
    { id: 265, name: 'فسا', provinceId: 17 },
    { id: 266, name: 'داراب', provinceId: 17 },
    { id: 267, name: 'لارستان', provinceId: 17 },
    { id: 268, name: 'لامرد', provinceId: 17 },
    { id: 269, name: 'گراش', provinceId: 17 },
    { id: 270, name: 'فراشبند', provinceId: 17 },
    { id: 271, name: 'قیر و کارزین', provinceId: 17 },
    { id: 272, name: 'مهر', provinceId: 17 },
    { id: 273, name: 'استهبان', provinceId: 17 },
    { id: 274, name: 'نی ریز', provinceId: 17 },
    { id: 275, name: 'بوانات', provinceId: 17 },
    { id: 276, name: 'ارسنجان', provinceId: 17 },
    { id: 277, name: 'سروستان', provinceId: 17 },
    { id: 278, name: 'کوار', provinceId: 17 },
    { id: 279, name: 'خرامه', provinceId: 17 },
    { id: 280, name: 'زرقان', provinceId: 17 },
    { id: 281, name: 'کوهنجان', provinceId: 17 },
    { id: 282, name: 'بیضا', provinceId: 17 },
    { id: 283, name: 'خنج', provinceId: 17 },
    { id: 284, name: 'قیر', provinceId: 17 },
    { id: 285, name: 'کارزین', provinceId: 17 },
    { id: 286, name: 'میمند', provinceId: 17 },
    { id: 287, name: 'سپیدان', provinceId: 17 },
    { id: 288, name: 'رستم', provinceId: 17 },
    { id: 289, name: 'ممسنی', provinceId: 17 },
    { id: 290, name: 'بختگان', provinceId: 17 },

    // قزوین
    { id: 291, name: 'قزوین', provinceId: 18 },
    { id: 292, name: 'البرز', provinceId: 18 },
    { id: 293, name: 'آبیک', provinceId: 18 },
    { id: 294, name: 'بوئین‌زهرا', provinceId: 18 },
    { id: 295, name: 'تاکستان', provinceId: 18 },
    { id: 296, name: 'محمودآباد', provinceId: 18 },
    { id: 297, name: 'آبگرم', provinceId: 18 },
    { id: 298, name: 'رودبار الموت', provinceId: 18 },
    { id: 299, name: 'رودبار شهرستان', provinceId: 18 },
    { id: 300, name: 'کوهین', provinceId: 18 },

    // قم
    { id: 301, name: 'قم', provinceId: 19 },
    { id: 302, name: 'جعفریه', provinceId: 19 },
    { id: 303, name: 'قنوات', provinceId: 19 },
    { id: 304, name: 'سلفچگان', provinceId: 19 },
    { id: 305, name: 'کهک', provinceId: 19 },

    // کردستان
    { id: 306, name: 'سنندج', provinceId: 20 },
    { id: 307, name: 'مریوان', provinceId: 20 },
    { id: 308, name: 'بانه', provinceId: 20 },
    { id: 309, name: 'سقز', provinceId: 20 },
    { id: 310, name: 'قروه', provinceId: 20 },
    { id: 311, name: 'کامیاران', provinceId: 20 },
    { id: 312, name: 'دیواندره', provinceId: 20 },
    { id: 313, name: 'دهگلان', provinceId: 20 },
    { id: 314, name: 'سروآباد', provinceId: 20 },
    { id: 315, name: 'کرانی', provinceId: 20 },

    // کرمان
    { id: 316, name: 'کرمان', provinceId: 21 },
    { id: 317, name: 'رفسنجان', provinceId: 21 },
    { id: 318, name: 'سیرجان', provinceId: 21 },
    { id: 319, name: 'بم', provinceId: 21 },
    { id: 320, name: 'جیرفت', provinceId: 21 },
    { id: 321, name: 'زرند', provinceId: 21 },
    { id: 322, name: 'بردسیر', provinceId: 21 },
    { id: 323, name: 'شهربابک', provinceId: 21 },
    { id: 324, name: 'بافت', provinceId: 21 },
    { id: 325, name: 'راور', provinceId: 21 },
    { id: 326, name: 'کوهبنان', provinceId: 21 },
    { id: 327, name: 'انار', provinceId: 21 },
    { id: 328, name: 'رابر', provinceId: 21 },
    { id: 329, name: 'ریگان', provinceId: 21 },
    { id: 330, name: 'فهرج', provinceId: 21 },
    { id: 331, name: 'عنبرآباد', provinceId: 21 },
    { id: 332, name: 'منوجان', provinceId: 21 },
    { id: 333, name: 'فاریاب', provinceId: 21 },
    { id: 334, name: 'قلعه گنج', provinceId: 21 },
    { id: 335, name: 'کهنوج', provinceId: 21 },

    // کرمانشاه
    { id: 336, name: 'کرمانشاه', provinceId: 22 },
    { id: 337, name: 'اسلام‌آباد غرب', provinceId: 22 },
    { id: 338, name: 'پاوه', provinceId: 22 },
    { id: 339, name: 'جوانرود', provinceId: 22 },
    { id: 340, name: 'هرسین', provinceId: 22 },
    { id: 341, name: 'سنقر', provinceId: 22 },
    { id: 342, name: 'کنگاور', provinceId: 22 },
    { id: 343, name: 'گیلانغرب', provinceId: 22 },
    { id: 344, name: 'روانسر', provinceId: 22 },
    { id: 345, name: 'ثلاث باباجانی', provinceId: 22 },
    { id: 346, name: 'قصر شیرین', provinceId: 22 },
    { id: 347, name: 'سرپل ذهاب', provinceId: 22 },
    { id: 348, name: 'دالاهو', provinceId: 22 },
    { id: 349, name: 'حمیل', provinceId: 22 },
    { id: 350, name: 'باینگان', provinceId: 22 },

    // کهگیلویه و بویراحمد
    { id: 351, name: 'یاسوج', provinceId: 23 },
    { id: 352, name: 'گچساران', provinceId: 23 },
    { id: 353, name: 'دوگنبدان', provinceId: 23 },
    { id: 354, name: 'دهدشت', provinceId: 23 },
    { id: 355, name: 'لیکک', provinceId: 23 },
    { id: 356, name: 'چرام', provinceId: 23 },
    { id: 357, name: 'پاتاوه', provinceId: 23 },
    { id: 358, name: 'سی‌سخت', provinceId: 23 },
    { id: 359, name: 'مادوان', provinceId: 23 },
    { id: 360, name: 'گراب', provinceId: 23 },

    // گلستان
    { id: 361, name: 'گرگان', provinceId: 24 },
    { id: 362, name: 'گنبد کاووس', provinceId: 24 },
    { id: 363, name: 'علی‌آباد', provinceId: 24 },
    { id: 364, name: 'آق‌قلا', provinceId: 24 },
    { id: 365, name: 'کردکوی', provinceId: 24 },
    { id: 366, name: 'بندر ترکمن', provinceId: 24 },
    { id: 367, name: 'کلاله', provinceId: 24 },
    { id: 368, name: 'آزادشهر', provinceId: 24 },
    { id: 369, name: 'رامیان', provinceId: 24 },
    { id: 370, name: 'مینودشت', provinceId: 24 },
    { id: 371, name: 'گالیکش', provinceId: 24 },
    { id: 372, name: 'مراوه‌تپه', provinceId: 24 },
    { id: 373, name: 'گمیشان', provinceId: 24 },
    { id: 374, name: 'سیمین‌شهر', provinceId: 24 },
    { id: 375, name: 'اینچه‌برون', provinceId: 24 },

    // گیلان
    { id: 376, name: 'رشت', provinceId: 25 },
    { id: 377, name: 'انزلی', provinceId: 25 },
    { id: 378, name: 'لاهیجان', provinceId: 25 },
    { id: 379, name: 'لنگرود', provinceId: 25 },
    { id: 380, name: 'رودسر', provinceId: 25 },
    { id: 381, name: 'فومن', provinceId: 25 },
    { id: 382, name: 'صومعه‌سرا', provinceId: 25 },
    { id: 383, name: 'ماسال', provinceId: 25 },
    { id: 384, name: 'رودبار', provinceId: 25 },
    { id: 385, name: 'منجیل', provinceId: 25 },
    { id: 386, name: 'املش', provinceId: 25 },
    { id: 387, name: 'تالش', provinceId: 25 },
    { id: 388, name: 'آستارا', provinceId: 25 },
    { id: 389, name: 'آستانه اشرفیه', provinceId: 25 },
    { id: 390, name: 'رودبنه', provinceId: 25 },
    { id: 391, name: 'کلاچای', provinceId: 25 },
    { id: 392, name: 'چابکسر', provinceId: 25 },
    { id: 393, name: 'سیاهکل', provinceId: 25 },
    { id: 394, name: 'شفت', provinceId: 25 },
    { id: 395, name: 'رضوانشهر', provinceId: 25 },

    // لرستان
    { id: 396, name: 'خرم‌آباد', provinceId: 26 },
    { id: 397, name: 'بروجرد', provinceId: 26 },
    { id: 398, name: 'دورود', provinceId: 26 },
    { id: 399, name: 'الیگودرز', provinceId: 26 },
    { id: 400, name: 'کوهدشت', provinceId: 26 },
    { id: 401, name: 'پل‌دختر', provinceId: 26 },
    { id: 402, name: 'ازنا', provinceId: 26 },
    { id: 403, name: 'نورآباد', provinceId: 26 },
    { id: 404, name: 'پاپی', provinceId: 26 },
    { id: 405, name: 'رومشکان', provinceId: 26 },

    // مازندران
    { id: 406, name: 'ساری', provinceId: 27 },
    { id: 407, name: 'بابل', provinceId: 27 },
    { id: 408, name: 'آمل', provinceId: 27 },
    { id: 409, name: 'قائم‌شهر', provinceId: 27 },
    { id: 410, name: 'بهشهر', provinceId: 27 },
    { id: 411, name: 'بابلسر', provinceId: 27 },
    { id: 412, name: 'سوادکوه', provinceId: 27 },
    { id: 413, name: 'نوشهر', provinceId: 27 },
    { id: 414, name: 'نور', provinceId: 27 },
    { id: 415, name: 'تنکابن', provinceId: 27 },
    { id: 416, name: 'رامسر', provinceId: 27 },
    { id: 417, name: 'چالوس', provinceId: 27 },
    { id: 418, name: 'محمودآباد', provinceId: 27 },
    { id: 419, name: 'فریدونکنار', provinceId: 27 },
    { id: 420, name: 'جویبار', provinceId: 27 },
    { id: 421, name: 'گلوگاه', provinceId: 27 },
    { id: 422, name: 'ساری', provinceId: 27 },
    { id: 423, name: 'میاندورود', provinceId: 27 },
    { id: 424, name: 'سوادکوه شمالی', provinceId: 27 },
    { id: 425, name: 'نکا', provinceId: 27 },

    // مرکزی
    { id: 426, name: 'اراک', provinceId: 28 },
    { id: 427, name: 'ساوه', provinceId: 28 },
    { id: 428, name: 'خمین', provinceId: 28 },
    { id: 429, name: 'دلیجان', provinceId: 28 },
    { id: 430, name: 'محلات', provinceId: 28 },
    { id: 431, name: 'شازند', provinceId: 28 },
    { id: 432, name: 'تفرش', provinceId: 28 },
    { id: 433, name: 'آشتیان', provinceId: 28 },
    { id: 434, name: 'فراهان', provinceId: 28 },
    { id: 435, name: 'کمیجان', provinceId: 28 },
    { id: 436, name: 'زالیان', provinceId: 28 },
    { id: 437, name: 'خنداب', provinceId: 28 },
    { id: 438, name: 'مهاجران', provinceId: 28 },
    { id: 439, name: 'نوبران', provinceId: 28 },
    { id: 440, name: 'شهباز', provinceId: 28 },

    // هرمزگان
    { id: 441, name: 'بندرعباس', provinceId: 29 },
    { id: 442, name: 'بندر لنگه', provinceId: 29 },
    { id: 443, name: 'قشم', provinceId: 29 },
    { id: 444, name: 'کیش', provinceId: 29 },
    { id: 445, name: 'بندر خمیر', provinceId: 29 },
    { id: 446, name: 'بستک', provinceId: 29 },
    { id: 447, name: 'حاجی‌آباد', provinceId: 29 },
    { id: 448, name: 'رودان', provinceId: 29 },
    { id: 449, name: 'میناب', provinceId: 29 },
    { id: 450, name: 'سیریک', provinceId: 29 },
    { id: 451, name: 'جاسک', provinceId: 29 },
    { id: 452, name: 'بشاگرد', provinceId: 29 },
    { id: 453, name: 'پارسیان', provinceId: 29 },
    { id: 454, name: 'ابوموسی', provinceId: 29 },
    { id: 455, name: 'تنب بزرگ', provinceId: 29 },
    { id: 456, name: 'تنب کوچک', provinceId: 29 },
    { id: 457, name: 'لاوان', provinceId: 29 },
    { id: 458, name: 'هنگام', provinceId: 29 },
    { id: 459, name: 'فرور', provinceId: 29 },
    { id: 460, name: 'شیدور', provinceId: 29 },

    // همدان
    { id: 461, name: 'همدان', provinceId: 30 },
    { id: 462, name: 'ملایر', provinceId: 30 },
    { id: 463, name: 'تویسرکان', provinceId: 30 },
    { id: 464, name: 'کبودرآهنگ', provinceId: 30 },
    { id: 465, name: 'نهاوند', provinceId: 30 },
    { id: 466, name: 'اسدآباد', provinceId: 30 },
    { id: 467, name: 'بهار', provinceId: 30 },
    { id: 468, name: 'رزن', provinceId: 30 },
    { id: 469, name: 'فامنین', provinceId: 30 },
    { id: 470, name: 'قهاوند', provinceId: 30 },

    // یزد
    { id: 471, name: 'یزد', provinceId: 31 },
    { id: 472, name: 'اردکان', provinceId: 31 },
    { id: 473, name: 'میبد', provinceId: 31 },
    { id: 474, name: 'ابرکوه', provinceId: 31 },
    { id: 475, name: 'مهریز', provinceId: 31 },
    { id: 476, name: 'بافق', provinceId: 31 },
    { id: 477, name: 'ابرکوه', provinceId: 31 },
    { id: 478, name: 'تفت', provinceId: 31 },
    { id: 479, name: 'خاتم', provinceId: 31 },
    { id: 480, name: 'بهاباد', provinceId: 31 }
];

module.exports = cities;

