const provinces = [
    { id: 1, name: 'آذربایجان شرقی', code: 'AZE' },
    { id: 2, name: 'آذربایجان غربی', code: 'AZW' },
    { id: 3, name: 'اردبیل', code: 'ARD' },
    { id: 4, name: 'اصفهان', code: 'ISF' },
    { id: 5, name: 'البرز', code: 'ALB' },
    { id: 6, name: 'ایلام', code: 'ILM' },
    { id: 7, name: 'بوشهر', code: 'BUS' },
    { id: 8, name: 'تهران', code: 'TEH' },
    { id: 9, name: 'چهارمحال و بختیاری', code: 'CHB' },
    { id: 10, name: 'خراسان جنوبی', code: 'KHS' },
    { id: 11, name: 'خراسان رضوی', code: 'KHR' },
    { id: 12, name: 'خراسان شمالی', code: 'KHN' },
    { id: 13, name: 'خوزستان', code: 'KHZ' },
    { id: 14, name: 'زنجان', code: 'ZAN' },
    { id: 15, name: 'سمنان', code: 'SMN' },
    { id: 16, name: 'سیستان و بلوچستان', code: 'SIB' },
    { id: 17, name: 'فارس', code: 'FAR' },
    { id: 18, name: 'قزوین', code: 'QAZ' },
    { id: 19, name: 'قم', code: 'QOM' },
    { id: 20, name: 'کردستان', code: 'KUR' },
    { id: 21, name: 'کرمان', code: 'KER' },
    { id: 22, name: 'کرمانشاه', code: 'KSH' },
    { id: 23, name: 'کهگیلویه و بویراحمد', code: 'KOH' },
    { id: 24, name: 'گلستان', code: 'GOL' },
    { id: 25, name: 'گیلان', code: 'GIL' },
    { id: 26, name: 'لرستان', code: 'LOR' },
    { id: 27, name: 'مازندران', code: 'MAZ' },
    { id: 28, name: 'مرکزی', code: 'MAR' },
    { id: 29, name: 'هرمزگان', code: 'HOR' },
    { id: 30, name: 'همدان', code: 'HAM' },
    { id: 31, name: 'یزد', code: 'YAZ' }
];

module.exports = provinces;

